qings/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views
from django.contrib.auth import views as auth_views

urlpatterns = staticfiles_urlpatterns()

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path("poets", views.poets, name="poets"),
    path('about', views.about, name="about"),
    path("quotes", views.quotes, name="quotes"),
    path("contacts", views.contacts, name="contacts"),
    path("videos", views.videos, name="videos"),
    path('blogs', views.BlogList.as_view(), name='blogs'),
    path('<slug:slug>/', views.Detail.as_view(), name='details'),
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

qingspoet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = staticfiles_urlpatterns()


urlpatterns = [
    path('admin/', admin.site.urls),
    path("qings/", include("qings.urls")),
    path("", include("qings.urls")),
]


if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

qings/models.py
from django.db import models

from django.contrib.auth.models import User
# Create your models here.

class Poet(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='static/%y')
    description = models.TextField()

    def __str__(self):
        return self.title


class Quote(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='static/%y')
    description = models.TextField()


    def __str__(self):
        return self.title
    

class Video(models.Model):
    title = models.CharField(max_length=200)
    video = models.FileField(upload_to='video/%y')
    description = models.TextField()


    def __str__(self):
        return self.title

    
class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name

STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Blog(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

qings/forms.py
from django import forms


class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField()

qings/views.py
from django.shortcuts import render
from django.template import loader
from .models import Poet, Quote, Video, Contact, Blog
from django.http import Http404, HttpResponse
from django.shortcuts import redirect
from django.urls import reverse

from django.views import generic
#contact us page
from django.core.mail import send_mail
from django.http import HttpResponse, HttpResponseRedirect
from qings.forms import ContactUsForm
from django.views.generic.base import TemplateView

from . import views
# Create your views here.

# def index(request):
#     return render(request, "qings/index.html")
class Index(TemplateView):
	template_name = 'qings/index.html'

def poets(request):
    poets = Poet.objects.all()
    if poets is not None:
        return render(request, "qings/poets.html", {"poets": poets})
    else:
        raise Http404('Image not display!')

def about(request):
    return render(request, "qings/about.html")

def quotes(request):
    quotes = Quote.objects.all()
    if quotes is not None:
        return render(request, "qings/quotes.html", {"quotes": quotes})
    else:
        raise Http404('Not accepted!')
    
def videos(request):
    videos = Video.objects.all()
    if videos is not None:
        return render(request, "qings/videos.html", {"videos": videos})
    else:
        raise Http404('No video!')

def contacts(request):
    if request.method=="POST":
        contact=Contact()
        name=request.POST.get('name')
        email=request.POST.get('email')
        message=request.POST.get('message')
        contact.name=name
        contact.email=email
        contact.message=message
        contact.save()
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "qings/contacts.html")
 

class BlogList(generic.ListView):
    queryset = Blog.objects.filter(status=1).order_by('-created_on')
    template_name = 'qings/blogs.html'

class Detail(generic.DetailView):
    model = Blog
    template_name = 'qings/details.html'



""""def contacts(request):
    if request.method == 'POST':
        # create an instance of our form, and fill it with the POST data
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data["name"] or "anonymous"} via Qingspoet Contact Us form',
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['admin@qingspoet.xyz'],
            )
            return HttpResponseRedirect('/email_sent/')
        # if the form is not valid, we let execution continue to the return
        # statement below, and display the form again (with errors).

    else:
        # this must be a GET request, so create an empty form
        form = ContactUsForm()

    return render(request,
                  'qings/contacts.html',
                  {'form': form})

def email_sent(request):
    return render(request, 'qings/email_sent.html') """

qings/templates/qings/about.html
{% extends "qings/layout.html" %}
{% load static %}

{% block title %}About | {% endblock %}

{% block body %}

        <div class="container" style="width: 100%;">
            <nav class="navbar navbar-expand-lg navbar-light bg-light d-inline-flex p-2 bd-highlight">
            <div class="container-fluid">
                <a class="btn btn-outline-primary btn-floating m-1" href="{% url 'index' %}"><strong>Qings Poet</strong></a>
            </div>
            </nav>
        </div>

        <div class="container">
            <header>
                <div class="zoom">
                    <h1 style="color: white;">ABOUT</h1>
                </div>
            </header>
        </div>

        <div class="container" style="text-align:center; box-shadow: 0 16px 48px #E3E7EB;">
            <div class="column mb-3">
                <div class="card">
                  <img src="{% static 'qings/media/qingsabout.jpg' %}" alt="thumbnail" style="width:20%; align-self: center;">
                  <div class="container">
                    <h2>Leeda Marine (Qings)</h2>
                    <p class="title"><strong>Owner</strong></p>
                    <p>Phenomenon Poetic, talented creative, lyricalist.</p>
                    <p><strong>Qingspoet: </strong>Is a true definition that gives overview expressions from the heart and soul,<br>
                        which defines us as humans. In the creation of Man, Love, Emotions, Struggles, and Affections<br>
                        was something that makes us different from any other living things in the universe.<br> 
                        This App was designed to help mankind to learn and to appreciate what love is.</p>
                        <p>Here at <strong>Qingspoet</strong> you are about to experience the true nature of human expressions<br>
                        and motivational quotes that will uplift the mind and growth. Man can't do it alone <br>
                        and so we all need words that can change our mindsets, words that can encourage us <br>
                        to strives. Motivational quotes are words that filled our souls with other sights to <br>
                        view all our difficulty in life and interwhine it to focus on life.</p>
                        <p>This is the reason why <strong>Qingspoet</strong> came to an existance, to support and ellivate mankind <br>
                        to be hopeful in Love and growth. Stay with us as we give out new updates for both poets <br>
                        and motivational quotes to spicy up all of the emotional and life struggles.</p>
                </div>
            </div>
        </div>

        <div class="container" style="background-color: rgb(156, 132, 156); width:auto; color: white;">
            <h2>Comments</h2>
            <div id="myCarousel" class="carousel slide text-center" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
            </ol>
        
            <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox" style="color: black;">
                    <div class="item active">
                    <h4>"This is the best thing you done and it as impact my life.<br> I am so happy with the result!"<br><span>Michael Roe, New York, USA.</span></h4>
                    </div>
                    <div class="item">
                    <h4>"One good thing... WOW!!"<br><span>John Doe, ATL, USA.</span></h4>
                    </div>
                    <div class="item">
                    <h4>"Could I... BE any more happy with this site? Lol!"<br><span>Chandler Bing, Ontario, Canada.</span></h4>
                    </div>
                    <div class="item">
                    <h4>"We appreciate your work... WOW!!"<br><span>Kelly Jones, CA, USA.</span></h4>
                    </div>
                </div>
        
            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
            </div>
        </div>
      

{% endblock %}

qings/templates/qings/blogs.html
{% extends "qings/layout.html" %}
{% load static %}
{% block title %}Blog Post | {% endblock %}

{% block body %}

    <div class="container" style="width: 100%;">
        <nav class="navbar navbar-expand-lg navbar-light bg-light d-inline-flex p-2 bd-highlight">
        <div class="container-fluid">
            <a class="btn btn-outline-primary btn-floating m-1" href="{% url 'index' %}"><strong>Qings Poet</strong></a>
        </div>
        </nav>
    </div>

    <div class="container">
        <header>
            <div class="zoom">
                <h1 style="color: white;">BLOG POST</h1>
            </div>
        </header>
    </div>

    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8 mt-3 left">
                {% for blog in blog_list %}
                <div class="card mb-4" style="box-shadow: 0 16px 48px #E3E7EB;">
                    <div class="card-body">
                        <h2 class="card-title">{{ blog.title }}</h2>
                        <p class="card-text text-muted h6">{{ blog.author }} | {{ blog.created_on}} </p>
                        <p class="card-text">{{blog.content|slice:":200" }}</p>
                        <a href="{% url 'details' blog.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                    </div>
                </div>
                {% endfor %}
            </div>
          
        </div>
    </div>
{%endblock%}

qings/templates/qings/contacts.html
{% extends "qings/layout.html" %}
{% load static %}
{% block title %}Contacts | {% endblock %}

{% block body %}

        <div class="container" style="width: 100%;">
            <nav class="navbar navbar-expand-lg navbar-light bg-light d-inline-flex p-2 bd-highlight">
            <div class="container-fluid">
                <a class="btn btn-outline-primary btn-floating m-1" href="{% url 'index' %}"><strong>Qings Poet</strong></a>
            </div>
            </nav>
        </div>

        <div class="container">
            <header>
                <div class="zoom">
                    <h1 style="color: white;">CONTACT US</h1>
                </div>
            </header>
        </div>

          <!--Contact form with a textarea for contacting the Author-->
        <div class="container py-4" style="background-color: gray; color: #ffffff; box-shadow: 0 16px 48px #E3E7EB;">

                <!-- Bootstrap 5 starter form -->
            <form id="contactForm" method="post">
            {% csrf_token %}
            
                <div class="form-group">
                    <label for="fname">Your Name</label>
                    <input name="name" type="text" id="fname" class="form-control" placeholder="Your Name">

                    <label for="exampleInputEmail">Email Address</label>
                    <input name="email" class="form-control" id="exampleInputEmail" placeholder="Email Address" aria-describedby="emailHelp" data-sb-validations="required, email" />
                    <div class="invalid-feedback" data-sb-feedback="emailAddress:required">Email Address is required.</div>

                    <label class="form-label" for="message">Message</label>
                    <textarea name="message" class="form-control" id="message" type="text" placeholder="Message" style="height: 20rem;" data-sb-validations="required"></textarea>
                    <div class="invalid-feedback" data-sb-feedback="message:required">Message is required.</div>

                    <input type="submit" class="btn btn-primary btn-lg mt-1 ml-4" value="Submit">

                </div>
            
            </form>
          
        </div>
          
          <!-- SB Forms JS -->
          <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>


        <div class="container" style="background-color: rgb(156, 132, 156); width:auto; text-align: center; color: white;">
            <h2>Comments</h2>
            <div id="myCarousel" class="carousel slide text-center" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
            </ol>
        
            <!-- Wrapper for slides -->
                <div class="carousel-inner" role="listbox" style="color: black;">
                    <div class="item active">
                    <h4>"The respond to my message was ontime.<br> I am so happy with the result!"<br><span>Mariam Grey, Texas, USA.</span></h4>
                    </div>
                    <div class="item">
                    <h4>"I was so excited to get a message back"<br><span>Franco Bas, Paris, Italy</span></h4>
                    </div>
                    <div class="item">
                    <h4>"Quick reply!!!"<br><span>Lisa Mari, Johanasbour, South Africa</span></h4>
                    </div>
                    <div class="item">
                    <h4>"No waiting for long for a respond"<br><span>Aliyu Galadima, Niger State, Nigeria</span></h4>
                    </div>
                </div>
        
            <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
            </div>
        </div>

{% endblock %}

qings/templates/qings/details.html
{% extends "qings/layout.html" %}
{% load static %}
{% block title %}Details Blog Post | {% endblock %}

{% block body %}

    <div class="container" style="width: 100%;">
        <nav class="navbar navbar-expand-lg navbar-light bg-light d-inline-flex p-2 bd-highlight">
        <div class="container-fluid">
            <a class="btn btn-outline-primary btn-floating m-1" href="{% url 'index' %}"><strong>Qings Poet</strong></a>
        </div>
        </nav>
    </div>

    <div class="container">
        <header>
            <div class="zoom">
                <h1 style="color: white;">DETAILS BLOG POST</h1>
            </div>
        </header>
    </div>

    <div class="container">
        <div class="row">
          <div class="col-md-8 card mb-4  mt-3 left  top" style="box-shadow: 0 16px 48px #E3E7EB;">
            <div class="card-body">
              <h3>{{ object.title }}</h3>
              <p class=" text-muted">{{ blog.author }} | {{ blog.created_on }}</p>
              <p class="card-text ">{{ object.content | safe }}</p>
            </div>
          </div>
        
        </div>
    </div>
      
{% endblock %}

qings/templates/qings/index.html
{% extends "qings/layout.html" %}

{% load static %}

{% block body %}
   
            <div id="mySidebar" class="sidebar">
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                <a href="{% url 'about' %}">About</a>
                <a href="{% url 'poets' %}">Poems</a>
                <a href="{% url 'quotes' %}">Motivational Quotes</a>
                <a href="{% url 'videos' %}">Videos</a>
                <a href="{% url 'blogs' %}">Blog Post</a>
                <a href="{% url 'contacts' %}">Contacts</a>
            </div>
            <div id="main">
                <button class="openbtn" onclick="openNav()">☰ Qings Poet</button>
            </div>

            <script>
                function openNav() {
                document.getElementById("mySidebar").style.width = "250px";
                document.getElementById("main").style.marginLeft = "250px";
                }
                
                function closeNav() {
                document.getElementById("mySidebar").style.width = "0";
                document.getElementById("main").style.marginLeft= "0";
                }
            </script>

            <div class="container">
                <header>
                    <div class="zoom">
                        <h1 style="color: white;">QINGS POETS AND MOTIVATIONAL QUOTES</h1>
                    </div>
                </header>
            </div>
    <section>
        <div class="container" style="width: 100%;">
            <div class="d-flex flex-row bd-highlight mb-3">
                <div class="card mx-3" style="width: 18rem; box-shadow: 0 16px 48px #E3E7EB;">
                    <img src="{% static 'qings/media/qingflo.png' %}" class="card-img-top" alt="home">
                    <div class="card-body" style="background-color: rgb(157, 145, 145);">
                    <h5 class="card-title"><strong>Poems</strong></h5>
                    <p class="card-text">For every sensations comes wih the beauty of the heart, lyrics that touches the soul, love that units mankind.</p>
                    <a href="{% url 'poets' %}" class="btn btn-primary d-flex flex-wrap">More &rarr;</a>
                    </div>
                </div>
                <div class="card mx-3" style="width: 18rem; box-shadow: 0 16px 48px #E3E7EB;">
                    <img src="{% static 'qings/media/qingmoti.png' %}" class="card-img-top" alt="home">
                    <div class="card-body">
                    <h5 class="card-title"><strong>Motivational Quotes</strong></b></h5>
                    <p class="card-text">Courage is not just only by actions but words can be the most strongest tools to push a man to his destination.</p>
                    <a href="{% url 'quotes' %}" class="btn btn-primary d-flex flex-wrap">More &rarr;</a>
                    </div>
                </div>
                <div class="card mx-3" style="width: 18rem; box-shadow: 0 16px 48px #E3E7EB;">
                    <img src="{% static 'qings/media/qingvideo.png' %}" class="card-img-top" alt="home">
                    <div class="card-body" style="background-color: rgb(157, 145, 145);">
                    <h5 class="card-title"><strong>Videos</strong></h5>
                    <p class="card-text">Watch super exclusive videos from poems sessions and power to rise motivational story line to uplift you.</p>
                    <a href="{% url 'videos' %}" class="btn btn-primary d-flex flex-wrap">More &rarr;</a>
                    </div>
                </div>
                <div class="card mx-3" style="width: 18rem; box-shadow: 0 16px 48px #E3E7EB;">
                    <img src="{% static 'qings/media/qingblog.png' %}" class="card-img-top" alt="home">
                    <div class="card-body">
                    <h5 class="card-title"><strong>Blog Post</strong></h5>
                    <p class="card-text">More excitement as you read more topics, stories, showing the over views of humanity from our blogger.</p>
                    <a href="{% url 'blogs' %}" class="btn btn-primary d-flex flex-wrap">More &rarr;</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

        <div class="container">
            <div id="carouselExampleDark" class="carousel carousel-light slide" data-bs-ride="carousel">
                <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
                <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="3" aria-label="Slide 4"></button>
                <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="4" aria-label="Slide 5"></button>
                </div>
                <div class="carousel-inner">
                <div class="carousel-item active" data-bs-interval="2000">
                    <img src="{% static 'qings/media/qingsdisplay.jpg' %}" class="d-block w-5%" style="width: 30%;" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                    <h1 class="btn btn-outline-primary"><strong>Recent Updates</strong></h1>
                    <p>Post recent content on regular bases,<br> <span>so always click in to see more favorite lines.</span></p>
                    </div>
                </div>
                <div class="carousel-item" data-bs-interval="2000">
                    <img src="{% static 'qings/media/qingquo4.png' %}" class="d-block w-5%" style="width: 30%;" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                    <h1 class="btn btn-outline-danger"><strong>Mission</strong></h1>
                    <p>On a mission to change humanity and increase<br> the beauty of the heart to respect Love and Affections.</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="{% static 'qings/media/qingsimg2.png' %}" class="d-block w-5%" style="width: 30%;" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                    <h1 class="btn btn-outline-info"><strong>No Regrets</strong></h1>
                    <p>Learn not to regret anything in life<br> not even our actions that was misunderstood.</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="{% static 'qings/media/qingquo.png' %}" class="d-block w-5%" style="width: 30%;" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                    <h1 class="btn btn-outline-success"><strong>Time</strong></h1>
                    <p>Time is one thing that can never stop for no man,<br> so why wasting it when you know it waits for no one.</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img src="{% static 'qings/media/qingwat.png' %}" class="d-block w-5%" style="width: 30%;" alt="...">
                    <div class="carousel-caption d-none d-md-block">
                    <h1 class="btn btn-outline-warning"><strong>Growth</strong></h1>
                    <p>Some people fail in growing cause of their own hinderance,<br> believe we all stand a chance to grow and develop. So take charge of your own growth.</p>
                    </div>
                </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>



{% endblock %}

qings/templates/qings/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="description" content="Is a true definition that gives overview expressions from the heart and soul,
    which defines us as humans. In the creation of Man, Love, Emotions, Struggles, and Affections
    was something that makes us different from any other living things in the universe.">
    <meta name="author" content="Mustapha Aliyu Galadima">
    {% load static %}
    <title>{% block title %}{% endblock %}Qingspoet</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'qings/styles.css' %}" rel="stylesheet">

        <!--Favicon for this project-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'qings/media/apple-touch-icon.png' %}">
    <link rel="icon" type="img/png" sizes="32x32" href="{% static 'qings/media/favicon-32x32.png' %}">
    <link rel="icon" type="img/png" sizes="16x16" href="{% static 'qings/media/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'qings/media/site.webmanifest' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'qings/media/favi.ico' %}">
    <!--Header for carousel of About, Poets, Quotes-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <!--Social media icons and link-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

    {% block body %}

    {% endblock %}  

        <hr>

        <footer class="bg-dark text-center text-white">
              
            Copy Rights <span>&copy; 2023 Qingspoet. All Rights Reserved</span>

                    <!-- Section: Social media -->
            <section class="mb-4">
                    <!-- Facebook -->
                <a class="btn btn-outline-primary btn-floating m-1" href="#!" role="button"><i class="fa fa-facebook"></i></a>
                    <!-- Twitter -->
                <a class="btn btn-outline-primary btn-floating m-1" href="#!" role="button"><i class="fa fa-twitter"></i></a>
                   <!-- Instagram -->
                <a class="btn btn-outline-danger btn-floating m-1" href="#!" role="button"><i class="fa fa-instagram"></i></a>
            </section>
        </footer>
      
</body>
</html>